services:
  postgres:
    image: postgres:17
    container_name: gtd_postgres
    environment:
      POSTGRES_USER: gtd_user
      POSTGRES_PASSWORD: gtd_password
      POSTGRES_DB: gtd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gtd_user -d gtd"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
